#!/bin/sh

# Define the UBUS event name
EVENT_NAME="hotplug.iface"

# Create JSON payload for UBUS event
JSON_PAYLOAD="{
    \"action\": \"$ACTION\",
    \"interface\": \"$INTERFACE\",
    \"device\": \"$DEVICE\",
    \"ifupdate_addresses\": \"$IFUPDATE_ADDRESSES\",
    \"ifupdate_routes\": \"$IFUPDATE_ROUTES\",
    \"ifupdate_prefixes\": \"$IFUPDATE_PREFIXES\",
    \"ifupdate_data\": \"$IFUPDATE_DATA\"
}"

# Send event to UBUS
ubus send "$EVENT_NAME" "$JSON_PAYLOAD"
