#!/bin/sh

# Define the UBUS event name
EVENT_NAME="hotplug.usb"

# Create JSON payload for UBUS event
JSON_PAYLOAD="{
    \"action\": \"$ACTION\",
    \"devicename\": \"$DEVICENAME\",
    \"devname\": \"$DEVNAME\",
    \"devnum\": \"$DEVNUM\",
    \"devpath\": \"$DEVPATH\",
    \"devtype\": \"$DEVTYPE\",
    \"type\": \"$TYPE\",
    \"product\": \"$PRODUCT\",
    \"seqnum\": \"$SEQNUM\",
    \"busnum\": \"$BUSNUM\",
    \"major\": \"$MAJOR\",
    \"minor\": \"$MINOR\"
}"

# Send event to UBUS
ubus send "$EVENT_NAME" "$JSON_PAYLOAD"
