#!/bin/sh

# Define the UBUS event name
EVENT_NAME="hotplug.net"

# Create JSON payload for UBUS event
JSON_PAYLOAD="{
    \"action\": \"$ACTION\",
    \"devicename\": \"$DEVICENAME\",
    \"path\": \"$PATH\",
    \"devpath\": \"$DEVPATH\",
    \"devtype\": \"$DEVTYPE\",
    \"interface\": \"$INTERFACE\",
    \"seqnum\": \"$SEQNUM\",
    \"subsystem\": \"$SUBSYSTEM\",
    \"ifindex\": \"$IFINDEX\"
}"

# Send event to UBUS
ubus send "$EVENT_NAME" "$JSON_PAYLOAD"
