#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
VM_DIR="$(dirname "$SCRIPT_DIR")"
ROOT_DIR="$(CDPATH= cd -- "$VM_DIR/../../.." && pwd)"
SSH="$VM_DIR/scripts/ssh"
SCP_TO="$VM_DIR/scripts/scp-to"
REMOTE="/tmp/devicecode-network-provider-fw4-schema-test"
WORK="$VM_DIR/work/network-provider-fw4-schema-test"

mkdir -p "$WORK"

if grep -R '"disable_ipv6"' "$ROOT_DIR/src/configs" >/dev/null 2>&1; then
  echo 'product config must not model disable_ipv6 as a firewall default' >&2
  grep -R '"disable_ipv6"' "$ROOT_DIR/src/configs" >&2 || true
  exit 1
fi


cat > "$WORK/run_openwrt_network_provider_fw4_schema.lua" <<'LUA'
package.path = table.concat({
  './src/?.lua',
  './src/?/init.lua',
  './vendor/lua-fibers/src/?.lua',
  './vendor/lua-fibers/src/?/init.lua',
  './vendor/lua-bus/src/?.lua',
  './vendor/lua-bus/src/?/init.lua',
  './vendor/lua-trie/src/?.lua',
  './vendor/lua-trie/src/?/init.lua',
  package.path,
}, ';')

local fibers = require 'fibers'
local sleep = require 'fibers.sleep'
local uci = require 'uci'
local provider_loader = require 'services.hal.backends.network.provider'
local perform = fibers.perform

local failures = {}
local function record(ok, msg)
  if not ok then failures[#failures + 1] = msg end
end
local function eq(a, b, msg)
  record(a == b, (msg or 'values differ') .. ': expected ' .. tostring(b) .. ', got ' .. tostring(a))
end
local function absent(v, msg)
  record(v == nil, (msg or 'value should be absent') .. ': got ' .. tostring(v))
end
local function contains(list, needle)
  if type(list) ~= 'table' then return list == needle end
  for i = 1, #list do if list[i] == needle then return true end end
  return false
end
local function wait_until(pred, timeout_s, label)
  local deadline = fibers.now() + (timeout_s or 1)
  while fibers.now() < deadline do
    if pred() then return true end
    perform(sleep.sleep_op(0.01))
  end
  if pred() then return true end
  fail(label or 'condition was not satisfied before timeout')
end

local function mkdir_p(path)
  local ok = os.execute("mkdir -p '" .. path .. "'")
  if ok ~= true and ok ~= 0 then error('mkdir failed for ' .. path) end
end
local function sorted_keys(t)
  local out = {}
  for k in pairs(t or {}) do out[#out + 1] = k end
  table.sort(out)
  return out
end

local tmp = '/tmp/dc-network-provider-fw4-schema'
os.execute("rm -rf '" .. tmp .. "'")
local conf = tmp .. '/conf'
local save = tmp .. '/save'
mkdir_p(conf)
mkdir_p(save)
for _, pkg in ipairs({ 'network', 'dhcp', 'firewall', 'mwan3' }) do
  local f = assert(io.open(conf .. '/' .. pkg, 'w'))
  f:write('# devicecode OpenWrt fw4 schema test\n')
  f:close()
end

local restarts = {}

-- Mirrors the generated firewall shape that caused live fw4 warnings: defaults,
-- zones, rules and forwardings are generated by the OpenWrt provider.
-- The provider must not write Devicecode-private metadata into firewall sections,
-- and the product-level intent must not contain unsupported fw4 defaults.
local intent = {
  schema = 'devicecode.net.intent/1',
  rev = 20260521,
  generation = 1,
  segments = {
    lan = {
      kind = 'lan',
      addressing = { ipv4 = { mode = 'static', cidr = '192.168.10.1/24' } },
      dhcp = { enabled = true, start = 100, limit = 150, leasetime = '12h' },
      firewall = { zone = 'lan' },
    },
    lan_rst = {
      kind = 'lan',
      addressing = { ipv4 = { mode = 'static', cidr = '192.168.20.1/24' } },
      dhcp = { enabled = true, start = 100, limit = 150, leasetime = '12h' },
      firewall = { zone = 'lan_rst' },
    },
    wan = {
      kind = 'wan',
      firewall = { zone = 'wan' },
    },
  },
  interfaces = {
    lan = {
      kind = 'bridge',
      role = 'lan',
      segment = 'lan',
      members = { 'eth0' },
      addressing = { ipv4 = { mode = 'static', cidr = '192.168.10.1/24' } },
    },
    lan_rst = {
      kind = 'bridge',
      role = 'lan',
      segment = 'lan_rst',
      members = { 'eth1' },
      addressing = { ipv4 = { mode = 'static', cidr = '192.168.20.1/24' } },
    },
    wan = {
      kind = 'ethernet',
      role = 'wan',
      segment = 'wan',
      endpoint = { ifname = 'eth2' },
      addressing = { ipv4 = { mode = 'dhcp', peerdns = false } },
    },
  },
  dns = {
    enabled = true,
    domain = 'bigbox.test',
    upstreams = { '1.1.1.1' },
    cache = { size = 512 },
  },
  dhcp = { defaults = { authoritative = true } },
  firewall = {
    defaults = {
      syn_flood = '1',
      input = 'ACCEPT',
      output = 'ACCEPT',
      forward = 'REJECT',
    },
    zones = {
      lan = { input = 'ACCEPT', output = 'ACCEPT', forward = 'REJECT' },
      lan_rst = { input = 'ACCEPT', output = 'ACCEPT', forward = 'REJECT' },
      wan = { input = 'REJECT', output = 'ACCEPT', forward = 'REJECT', masq = true, mtu_fix = true },
    },
    policies = {
      lan_to_wan_1 = { from = 'lan', to = 'wan' },
      lan_rst_to_wan_1 = { from = 'lan_rst', to = 'wan' },
    },
    rules = {
      Allow_DHCP_Renew = {
        name = 'Allow-DHCP-Renew', family = 'ipv4', src = 'wan', proto = 'udp', dest_port = '68', target = 'ACCEPT',
      },
      Allow_IGMP = {
        name = 'Allow-IGMP', family = 'ipv4', src = 'wan', proto = 'igmp', target = 'ACCEPT',
      },
      Allow_IPSec_ESP = {
        name = 'Allow-IPSec-ESP', src = 'wan', proto = 'esp', target = 'ACCEPT',
      },
      Allow_IPSec_ESP_RST = {
        name = 'Allow-IPSec-ESP (RST)', src = 'lan_rst', dest = 'wan', proto = 'esp', target = 'ACCEPT',
      },
      Allow_ISAKMP = {
        name = 'Allow-ISAKMP', src = 'wan', proto = 'udp', dest_port = '500', target = 'ACCEPT',
      },
      Allow_ISAKMP_RST = {
        name = 'Allow-ISAKMP (RST)', src = 'lan_rst', dest = 'wan', proto = 'udp', dest_port = '500', target = 'ACCEPT',
      },
      Allow_Ping = {
        name = 'Allow-Ping', src = 'wan', proto = 'icmp', icmp_type = 'echo-request', family = 'ipv4', target = 'ACCEPT',
      },
      Allow_DHCP_request_RST = {
        name = 'Allow DHCP request (RST)', src = 'lan_rst', proto = 'udp', dest_port = '67', target = 'ACCEPT',
      },
      Allow_DNS_queries_RST = {
        name = 'Allow DNS queries (RST)', src = 'lan_rst', proto = { 'tcp', 'udp' }, dest_port = '53', target = 'ACCEPT',
      },
    },
  },
  routing = {},
  wan = { enabled = true, members = { wan = { interface = 'wan', mwan_metric = 1, weight = 1 } } },
  shaping = {},
  vpn = {},
  diagnostics = {},
}

fibers.run(function(_scope)
  local provider, perr = provider_loader.new({
    provider = 'openwrt',
    confdir = conf,
    savedir = save,
    debounce_s = 0.01,
    run_cmd = function(argv)
      restarts[#restarts + 1] = table.concat(argv, ' ')
      return true, nil
    end,
  }, {})
  assert(provider, perr)

  local valid = perform(provider:validate_op({ intent = intent }))
  assert(valid and valid.ok == true, 'validate failed: ' .. tostring(valid and valid.err))

  local plan = perform(provider:plan_op({ intent = intent }))
  assert(plan and plan.ok == true, 'plan failed: ' .. tostring(plan and plan.err))
  assert(plan.plan.packages.firewall.changes > 0, 'firewall plan should have changes')

  local result = perform(provider:apply_op({ intent = intent }))
  assert(result and result.ok == true, 'apply failed: ' .. tostring(result and result.err))
  assert(result.activation == nil, 'provider activation should be synchronous for structural network apply')
  eq(#restarts, 4, 'activation command count')
  provider:terminate('test complete')
end)

eq(restarts[#restarts], '/etc/init.d/mwan3 restart', 'last restart command')

local c = assert(uci.cursor(conf, save))
if type(c.load) == 'function' then pcall(function() c:load('firewall') end) end

eq(c:get('firewall', 'defaults'), 'defaults', 'firewall.defaults type')
eq(c:get('firewall', 'zone_lan'), 'zone', 'firewall.zone_lan type')
eq(c:get('firewall', 'zone_lan_rst'), 'zone', 'firewall.zone_lan_rst type')
eq(c:get('firewall', 'zone_wan'), 'zone', 'firewall.zone_wan type')
eq(c:get('firewall', 'rule_Allow_DHCP_Renew'), 'rule', 'DHCP renew rule type')
eq(c:get('firewall', 'rule_Allow_DNS_queries_RST'), 'rule', 'RST DNS rule type')
record(contains(c:get('firewall', 'zone_lan', 'network'), 'lan'), 'zone_lan must contain lan network')
record(contains(c:get('firewall', 'zone_lan_rst', 'network'), 'lan_rst'), 'zone_lan_rst must contain lan_rst network')

-- These assertions encode the schema boundary: Devicecode-private ownership
-- markers must not be written into OpenWrt's firewall4-owned schema.
local sections = {}
c:foreach('firewall', nil, function(s)
  if type(s) == 'table' and type(s['.name']) == 'string' then
    sections[#sections + 1] = s['.name']
  end
end)
table.sort(sections)
for _, section in ipairs(sections) do
  absent(c:get('firewall', section, 'devicecode_managed'), 'firewall.' .. section .. '.devicecode_managed')
  absent(c:get('firewall', section, 'devicecode_owner'), 'firewall.' .. section .. '.devicecode_owner')
  absent(c:get('firewall', section, 'devicecode_semantic_id'), 'firewall.' .. section .. '.devicecode_semantic_id')
  absent(c:get('firewall', section, 'devicecode_role'), 'firewall.' .. section .. '.devicecode_role')
end

-- The higher-level product config no longer models disable_ipv6 as a firewall
-- default. This test therefore does not inject it; fw4 is the schema authority.
absent(c:get('firewall', 'defaults', 'disable_ipv6'), 'firewall.defaults.disable_ipv6')

print('FIREWALL_CONF=' .. conf .. '/firewall')
print('OPENWRT_PROVIDER_FW4_SCHEMA_UCI_CHECKS=' .. (#failures == 0 and 'ok' or 'failed'))
if #failures > 0 then
  for _, failure in ipairs(failures) do
    io.stderr:write('SCHEMA_VIOLATION: ', failure, '\n')
  end
  os.exit(1)
end
print('openwrt network provider fw4 schema UCI checks: ok')
LUA

"$SSH" "rm -rf '$REMOTE'; mkdir -p '$REMOTE'"
"$SCP_TO" "$ROOT_DIR/src" "$REMOTE/src"
"$SCP_TO" "$ROOT_DIR/vendor" "$REMOTE/vendor"
"$SCP_TO" "$WORK/run_openwrt_network_provider_fw4_schema.lua" "$REMOTE/run_openwrt_network_provider_fw4_schema.lua"

set +e
LUA_OUTPUT="$("$SSH" "cd '$REMOTE' && lua ./run_openwrt_network_provider_fw4_schema.lua" 2>&1)"
LUA_RC=$?
set -e
printf '%s\n' "$LUA_OUTPUT"

FW_FILE="$(printf '%s\n' "$LUA_OUTPUT" | sed -n 's/^FIREWALL_CONF=//p' | tail -n 1)"
if [ -z "$FW_FILE" ]; then
  echo 'failed to locate generated firewall config path in Lua output' >&2
  exit 1
fi

set +e
FW4_OUTPUT="$("$SSH" "set -eu
fw_file='$FW_FILE'
out=/tmp/devicecode-fw4-schema-check.out
backup=/tmp/devicecode-fw4-schema-firewall.backup
cp /etc/config/firewall \"\$backup\"
restore() { cp \"\$backup\" /etc/config/firewall; rm -f \"\$backup\"; }
trap restore EXIT INT TERM
cp \"\$fw_file\" /etc/config/firewall
set +e
fw4 check >\"\$out\" 2>&1
rc=\$?
set -e
cat \"\$out\"
if grep -E \"unknown option|not supported by fw4|specifies unknown option\" \"\$out\" >/dev/null 2>&1; then
  echo 'fw4 schema warnings were emitted for generated firewall config' >&2
  exit 1
fi
exit \"\$rc\"")"
FW4_RC=$?
set -e
printf '%s\n' "$FW4_OUTPUT"

if [ "$LUA_RC" -ne 0 ]; then
  echo "Lua-side generated UCI schema checks failed with rc=$LUA_RC" >&2
  exit "$LUA_RC"
fi
if [ "$FW4_RC" -ne 0 ]; then
  echo "fw4 schema check failed with rc=$FW4_RC" >&2
  exit "$FW4_RC"
fi

echo 'openwrt network provider fw4 schema: ok'
