#!/bin/sh

# Define the UBUS event name
EVENT_NAME="hotplug.ntp"

# Create JSON payload for UBUS event
JSON_PAYLOAD="{
    \"action\": \"$ACTION\",
    \"freq_drift_ppm\": \"$freq_drift_ppm\",
    \"offset\": \"$offset\",
    \"stratum\": \"$stratum\",
    \"poll_interval\": \"$poll_interval\"
}"

# Send event to UBUS
ubus send "$EVENT_NAME" "$JSON_PAYLOAD"
